config/routes.rb
Rails.application.routes.draw do
  resources :worker_projects
  resources :projects
  resources :workers do
    collection do
      get :search
    end
  end
  resources :departments
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/models/worker_project.rb
class WorkerProject < ActiveRecord::Base
  belongs_to :worker
  belongs_to :project
end

app/controllers/worker_projects_controller.rb
class WorkerProjectsController < ApplicationController
  before_action :set_worker_project, only: [:show, :edit, :update, :destroy]

  # GET /worker_projects
  # GET /worker_projects.json
  def index
    @worker_projects = WorkerProject.all
  end

  # GET /worker_projects/1
  # GET /worker_projects/1.json
  def show
  end

  # GET /worker_projects/new
  def new
    @worker_project = WorkerProject.new
  end

  # GET /worker_projects/1/edit
  def edit
  end

  # POST /worker_projects
  # POST /worker_projects.json
  def create
    @worker_project = WorkerProject.new(worker_project_params)

    respond_to do |format|
      if @worker_project.save
        format.html { redirect_to @worker_project, notice: 'Worker project was successfully created.' }
        format.json { render :show, status: :created, location: @worker_project }
      else
        format.html { render :new }
        format.json { render json: @worker_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worker_projects/1
  # PATCH/PUT /worker_projects/1.json
  def update
    respond_to do |format|
      if @worker_project.update(worker_project_params)
        format.html { redirect_to @worker_project, notice: 'Worker project was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker_project }
      else
        format.html { render :edit }
        format.json { render json: @worker_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worker_projects/1
  # DELETE /worker_projects/1.json
  def destroy
    @worker_project.destroy
    respond_to do |format|
      format.html { redirect_to worker_projects_url, notice: 'Worker project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker_project
      @worker_project = WorkerProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_project_params
      params.require(:worker_project).permit(:worker_id, :project_id,
        worker_attributes: [:id, :_destroy, :fn, :sn, :ln, :passport, :inn, :birthday]
      )
    end
end

app/helpers/worker_projects_helper.rb
module WorkerProjectsHelper
  # nested_start role->worker user->project
  def link_to_add_worker(form, project)
    # Создаём новый объект. Аналог build в ранних примерах
    new_object = WorkerProject.new()
    # Нам нужна nested-форма. В момент создания ссылки её ещё нет. Создадим её
    # Все worker_projects в форме имеют свой номер
    # Мы его пока заменям на фразу new_wp
    fields = form.fields_for(:worker_projects, new_object,
      :child_index => 'new_worker') do |fr|
      render('projects/one_worker_project_form', fr: fr, i: 'Новый')
    end
    # Ссылка будет обрабатываться javascript-ом поэтому адрес фиктивный
    link_to(?#, class: 'btn btn-info',
        id: 'add_worker_link', data: {content: "#{fields}"}) do
      fa_icon("plus") + " Новый сотрудник"
    end
  end

  def link_to_remove_worker(form)
    # При удалении nested-конструкции. Она реально не удаляется
    # Соответствующий html-блок скрывается
    # При этом выставляется значение специального поля _destroy
    # По этому поля rails понимает, что связь надо удалить
    form.hidden_field(:_destroy, class: 'remove_fields') +
        # Ссылка будет обрабатываться javascript-ом поэтому адрес фиктивный
        link_to(?#, class: 'remove_fields remove_worker') do
      fa_icon('times', title: 'Удалить сотрудника') + ' Удалить'
    end
  end
  # nested_finish
end

app/views/worker_projects/_form.html.haml
= form_for @worker_project do |f|
  - if @worker_project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@worker_project.errors.count, "error")} prohibited this worker_project from being saved:"
      %ul
        - @worker_project.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :worker
    = f.text_field :worker
  .field
    = f.label :project
    = f.text_field :project
  .actions
    = f.submit 'Save'

app/views/worker_projects/edit.html.haml
%h1 Editing worker_project

= render 'form'

= link_to 'Show', @worker_project
\|
= link_to 'Back', worker_projects_path

app/views/worker_projects/index.html.haml
%h1 Listing worker_projects

%table
  %thead
    %tr
      %th Worker
      %th Project
      %th
      %th
      %th

  %tbody
    - @worker_projects.each do |worker_project|
      %tr
        %td= worker_project.worker
        %td= worker_project.project
        %td= link_to 'Show', worker_project
        %td= link_to 'Edit', edit_worker_project_path(worker_project)
        %td= link_to 'Destroy', worker_project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Worker project', new_worker_project_path

app/views/worker_projects/new.html.haml
%h1 New worker_project

= render 'form'

= link_to 'Back', worker_projects_path

app/views/worker_projects/show.html.haml
%p#notice= notice

%p
  %b Worker:
  = @worker_project.worker
%p
  %b Project:
  = @worker_project.project

= link_to 'Edit', edit_worker_project_path(@worker_project)
\|
= link_to 'Back', worker_projects_path