config/routes.rb
Rails.application.routes.draw do
  resources :worker_projects
  resources :projects
  resources :workers do
    collection do
      get :search
    end
  end
  resources :departments
  resources :role_users
  resources :roles
  resources :password_resets

  get 'welcome/index', as: :welcome
  get 'welcome/insufficient_privileges', as: :ip
  get 'login' => 'welcome#new', :as => :login
  get 'logout' => 'welcome#destroy', :as => :logout
  post 'try_login' => 'welcome#create', :as => :try_login
  root 'welcome#index'

  resources :users do
    member do
      get :activate
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :require_login, except: [:destroy]
  skip_before_action :check_app_auth
  
  def index
  end 

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(root_path, notice: 'Вход выполнен')
    else
      flash[:danger] = "Неверный #{User.human_attribute_name(:email).mb_chars.downcase} или
#{User.human_attribute_name(:password).mb_chars.downcase}"
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(root_path, notice: 'Сеанс работы в системе завершен')
  end

  def insufficient_privileges
    @current_user_object = current_user
    @current_user_login = @current_user_object.email
    @current_role_user = RoleUser.where(id: params['bad_user_role']).first
  end  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_form.html.haml
= form_tag try_login_path, :method => :post do
  .row
    .col-md-6
      .form-group
        .input-group.input-group-md
          %span.input-group-addon.px50
            %i.fa.fa-user
          = text_field_tag :email, '', class: 'form-control', placeholder: User.human_attribute_name(:email)
  .row
    .col-md-6 
      .form-group
        .input-group.input-group-md
          %span.input-group-addon.px50
            %i.fa.fa-key
          = password_field_tag :password, '', class: 'form-control', placeholder: User.human_attribute_name(:password)
  .row
    .col-md-6 
      .checkbox
        %label
          = check_box_tag :remember_me, false, true
          Запомнить меня 
  .row
    .form-actions
      .col-md-2
        = submit_tag "Войти", class: 'btn btn-primary'
      .col-md-2      
        = link_to 'Забыли пароль?', new_password_reset_path, class: 'btn'
      .col-md-2
        = link_to 'Регистрация', new_user_path, class: 'btn'

app/views/welcome/index.html.haml
%h1 Добро пожаловать!

app/views/welcome/insufficient_privileges.html.haml
%h1 Недостаточно привилегий!

Пользователю
= @current_user_login
в роли
= @current_role_user.try(:role).try(:full_name)
недостаточно прав для доступа к методу 
= params['bad_action_name']
контроллера
= params['bad_controller_name']

app/views/welcome/new.html.haml
.page-header
  %h1
    Вход в 
    = t('app.name')

= render 'form'